### ISSUE TITLE
Posts not changing

### ISSUE THREAD

**Issue by mebble** [Anupam-dagar/reddit-scraper#1]
@Anupam-dagar [These lines](https://github.com/Anupam-dagar/reddit-scraper/blob/e7f42792c0bdb6b038cecffdb023481291cf7917/reddit-scraper.py#L17-L18) are returning the elements of the top navbar, which are the subreddits. This content won't change even if the `.next-button` url is requested.
We need a new selector that will return the host post elements instead.

**Comment by Anupam-dagar** [comment]
ohh :O thanx for finding the bug, let's work on this :smile:

**Comment by Anupam-dagar** [comment]
it's fixed now, thanx @mebble :smile:

**Comment by mebble** [comment]
Glad I could help :smiley:
